- src/functionalTest/java/org/spdx/SpdxSbomPluginFunctionalTest.java
- src/main/java/org/spdx/sbom/gradle/SpdxSbomExtension.java
- src/main/java/org/spdx/sbom/gradle/SpdxSbomPlugin.java
- src/main/java/org/spdx/sbom/gradle/project/ScmInfo.java
- src/main/java/org/spdx/sbom/gradle/utils/SpdxDocumentBuilder.java
This still doesn't populate download location yet, but it makes our sourceInfo entry more closely match that until we figure it out.
> make sourceInfo more closely match downloadLocation

- src/main/java/org/spdx/sbom/gradle/utils/SpdxKnownLicenses.java
- src/main/java/org/spdx/sbom/gradle/utils/SpdxKnownLicensesService.java
- src/main/resources/spdx-licenses.json
downloaded from https://spdx.org/licenses/licenses.json
So that builds using this plugin don't need to redownload this file, to improve determinism and reduce network requests
> embedded licenses.json file

- build.gradle.kts
- example.spdx.json
- src/main/java/org/spdx/sbom/gradle/SpdxSbomTask.java
- src/main/java/org/spdx/sbom/gradle/utils/SpdxDocumentBuilder.java
- use proper purl syntax
- remove unecessary rdf store creation
- update example again
> Update spdx library versions and fix purl

- build.gradle.kts
to improve threadsafety and reduce extra warnings
> spdx-java-library 1.1.6

- README.md
to make it easier to follow along
> README nullability update

- src/functionalTest/java/org/spdx/SpdxSbomPluginFunctionalTest.java
> Fix SpdxSbomPluginFunctionalTest after support for NOASSERTION in URL

- src/main/java/org/spdx/sbom/gradle/maven/MavenPackageSupplierBuilder.java
- src/main/java/org/spdx/sbom/gradle/maven/PomInfo.java
- src/main/java/org/spdx/sbom/gradle/maven/PomResolver.java
- src/main/java/org/spdx/sbom/gradle/utils/SpdxDocumentBuilder.java
- src/test/java/org/spdx/sbom/gradle/maven/MavenPackageSupplierBuilderTest.java
> Consider the developer's organization for the package supplier

- src/functionalTest/java/org/spdx/SpdxSbomPluginFunctionalTest.java
- src/main/java/org/spdx/sbom/gradle/SpdxSbomPlugin.java
So the spdxSbomForRelease task can be instantiated during project configuration time by the `tasks` task without having to also resolve its dependencies
Fixes: #62
> Lazy calculation of effective pom

- build.gradle.kts
> use more specific dependencies for maven

- src/main/java/org/spdx/sbom/gradle/SpdxSbomPlugin.java
- src/main/java/org/spdx/sbom/gradle/SpdxSbomTask.java
- src/main/java/org/spdx/sbom/gradle/project/ProjectInfoService.java
This should help with #25 
@liutikas @mathjeff does this help with android x build times?
> Compute all project info once

- README.md
- gradle.properties
waiting on https://github.com/spdx/spdx-gradle-plugin/actions/runs/6648187515
> Update after 0.3.0 release

- src/main/java/org/spdx/sbom/gradle/SpdxSbomTask.java
> Easy access to output file

- src/main/java/org/spdx/sbom/gradle/SpdxSbomPlugin.java
- There's an outstanding Gradle bug that requires this - https://github.com/gradle/gradle/issues/17295
> Include ArtifactRepository declared in settings

- README.md
- gradle.properties
0.4.0 is now on plugin portal: https://plugins.gradle.org/plugin/org.spdx.sbom
thanks @eygraber for all the updates and fixes on this release.
> update after 0.4.0 release

- src/main/java/org/spdx/sbom/gradle/maven/MavenPackageSupplierBuilder.java
- src/main/java/org/spdx/sbom/gradle/maven/PomResolver.java
- src/test/java/org/spdx/sbom/gradle/maven/MavenPackageSupplierBuilderTest.java
- See [tweetnacl-java](https://repo.maven.apache.org/maven2/org/purejava/tweetnacl-java/1.1.2/tweetnacl-java-1.1.2.pom) as an example
> Handle empty string fields from POM

- README.md
- gradle.properties
https://plugins.gradle.org/plugin/org.spdx.sbom/0.6.0 released
> update after 0.6.0 release

- .github/workflows/gradle.yml
- .github/workflows/release.yml
gradle-build-action is deprecated
> Use setup-gradle in actions

- README.md
- build.gradle.kts
- gradle.properties
0.7.0 is released: https://plugins.gradle.org/plugin/org.spdx.sbom/0.7.0
> update after 0.7.0 release

- build.gradle.kts
spdx-java library change https://github.com/spdx/Spdx-Java-Library/pull/228
> Upgrading java-spdx-library to 1.1.11 to handle file download location

- README.md
- build.gradle.kts
- gradle.properties
0.9.0 is on the plugin portal: https://plugins.gradle.org/plugin/org.spdx.sbom
> update after 0.9.0 release

- src/main/java/org/spdx/sbom/gradle/SpdxSbomPlugin.java
- src/main/java/org/spdx/sbom/gradle/utils/SpdxDocumentBuilder.java
- src/main/java/org/spdx/sbom/gradle/utils/SpdxLicenses.java
This PR fixes possible CME issues that we experience sometimes
Also added some license parsing exception details which also happen sometimes
> Avoid modifying project repositories
